name: 🙏 Problem - My seed words fail to restore coins
description: You entered your seed words and expected your coins to be found but they weren't.
assignees:
  - rt121212121
title: "[SUPPORT/RESTORATION] <edit this bit>"
labels: ["support", "Needs Triage"]
body:
- type: checkboxes
  attributes:
    label: Have you referred to our useful guide on how to restore coins with ElectrumSV?
    description: This guide shows you the nuances of restoring coins in different wallets.
    options:
    - label: I have read the [useful guide](https://rogertaylor.substack.com/p/how-do-i-import-my-seed-words) and tried what it describes.
      required: true
- type: dropdown
  id: version-source
  attributes:
    label: What version of ElectrumSV did you enter your seed words into?
    description: What version of our software are you running?
    options:
      - I will make you ask and delay how long it takes you to help me.
      - 1.3.16 (current release)
      - 1.3.17b1 (beta version)
      - 1.3.15
      - 1.3.14
      - 1.3.13
      - Mentioned under "Anything else?".
    default: 0
  validations:
    required: true
- type: dropdown
  id: version-os
  attributes:
    label: Which operating system is your ElectrumSV running on?
    description: What operating system are you using?
    options:
      - I will make you ask and delay how long it takes you to help me.
      - macOS 14 (Sonoma)
      - Windows 11
      - Linux (specific version mentioned under "Anything else")
      - macOS 13 (Sonoma)
      - macOS 12 (Ventura)
      - macOS 11 (Big Sur)
      - Windows 10
      - Mentioned under "Anything else?".
    default: 0
  validations:
    required: true
- type: dropdown
  id: version-destination
  attributes:
    label: Which wallet were your seed words from?
    description: Seed words are used differently in different wallets, which wallet did you get yours from?
    options:
      - I will make you ask and delay how long it takes you to help me.
      - CentBee
      - Electron Cash
      - Electrum Core
      - ElectrumSV
      - Exodus
      - HandCash
      - RockWallet
      - Tokenized
      - Mentioned under "Anything else?".
    default: 0
  validations:
    required: true
- type: textarea
  attributes:
    label: Observed behavior
    description: What you tried from the guide linked above, what you expected to happen and what you saw instead. If you do not fill this in, then you will be asked to provide this information before you get help.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the topic you are raising!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
